version: "3.8"
services:
  db2:
    image: postgres:15
    container_name: pg_15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - local_pgdata:/var/lib/postgresql/data

volumes:
  local_pgdata:
